compra=["pan","leche","huevos","carne","verduras"]
compra.append("frutas")
compra.append("cereal")
print("Lista de la compra actualizada:", compra)
compra.insert(2, "arroz")
print("Lista de la compra con arroz añadido en la posición 2:", compra)
print(compra)
compra.remove("carne")
print("Lista de la compra sin carne:", compra)
elemento_eliminado = compra.pop()
print("Elemento eliminado (último de la lista):", elemento_eliminado)
print("Lista de la compra final:", compra)
print("Cantidad de elementos en la lista de la compra:", len(compra))
print("¡He terminado de gestionar la lista de la compra!")